Repository casadodev/bot-twitch-python, pull requests merged in 2020-10, with the labels that each got.

#17 Generalize counters and add !risada
  bot.py
Labels: enhancement

#18 Improve how counters are created
  bot.py
Labels: bug

#22 Readme
  README.md
Labels: documentation

#26 ler o arquivo bot.py e cria a lista em files/commands.txt
  comands_list.sh
Labels: enhancement

#27 Atualizando informações
  bot.py
Labels: enhancement

#29 Update counters.json
  files/counters.json
Labels: enhancement

#31 Refactor & melhoria nos comandos
  bot.py
Labels: enhancement

#34 arrumando horasorteio
  bot.py
Labels: enhancement

#44 Line devcirino
  bot.py
  files/counters.json
Labels: bug
